### ISSUE TITLE
Arremates (checklist)

### ISSUE THREAD

**Issue by renanrdmachado** [renanrdmachado/trucado#1]
- [ ] **Cadastro**
  - [ ] Pré-cadastro com os plugins sociais
  - [ ] Aprovação do cadastro
  - [ ] Cadastro completo
----
- [ ] **Favoritos**
  - [ ] Possibilitar que os produtos sejam favoritados para exibir na lista de favoritos
  - [ ] Notificar usuário caso tenha feito alguma alteração no produto favorito
----
- [ ] **Arremates**
  - [ ] Criar arremate no admin
    - [ ] _Fields [name, product, start_at, end_at, active, status_auction*, price_initial, price_variation, best_price_auction*, best_user_auction*, price_for_sale*, data_auction¹]_
  - [ ] Exibir arremate no front
  - [ ] Dar lance
    - [ ] Escolher entre 3 opções pré-definidas (best_price_auction* + (price_variation*3))
  - [ ] Em cada arremate no admin, listar todos os lances e destacar o ganhador atual
  - [ ] Se um usuário atingir o price_for_sale*, concluir imediatamente o arremate e atualizar o status_auction*
  - [ ] Finalizar arremate. Notificar por e-mail o admin (vencedor) e o usuário vencedor (parabenizando)
  - [ ] Notificações
    - [ ] Avisar usuários dos arremates cadastrados
    - [ ] Avisar usuários que existe um novo arremate melhor que o dele
----
01) `
array() {
  ['auction_id'] => foreign int {
    [0] => {
      ['user_id'] => foreign int,
      ['auction_value'] => varchar,
      ['auction_date'] => date,
      ['auction_status'] => varchar
    }
    ...
  }
}
`
